[tool.poetry]
name = "compsyn"
version = "0.3.0"
description = "python package to explore the color of language"
authors = ["comp-syn"]

[tool.poetry.dependencies]
python = "^3.7"
google-api-core = "1.14.3"
google-auth = "1.6.3"
google-cloud = "0.34.0"
google-cloud-vision = "0.39.0"
google-images-download = "2.8.0"
googleapis-common-protos = "1.6.0"
notebook = "^6.0.3"
ipykernel = "^5.2.0"
python-rapidjson = "^0.9.1"
beautifulsoup4 = "^4.9.0"
pillow = "^7.1.1"
random_word = "^1.0.4"
nltk = "^3.4.5"
pandas = "^1.0.3"
textblob = "^0.15.3"
grpcio = "^1.28.1"
matplotlib = "^3.2.1"
numba = "^0.48.0"
sklearn = "^0.0"
scikit-learn = "^0.22.2"
scikit-image = "^0.16.2"
seaborn = "^0.10.0"
googletrans = "^2.4.0"
requests = "^2.23.0"
gensim = "^3.8.3"
memory_profiler = "^0.57.0"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
