name: Test
on:
  push: 

jobs:
  pytest:
    environment: ci
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.10

    - uses: snok/install-poetry@v1

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    
    - name: Install dependencies
      run: |
        poetry install

    - name: Run full pytest coverage 
      env:
        COMPSYN_S3_ACCESS_KEY_ID: ${{ secrets.COMPSYN_S3_ACCESS_KEY_ID }}
        COMPSYN_S3_SECRET_ACCESS_KEY: ${{ secrets.COMPSYN_S3_SECRET_ACCESS_KEY }}
        COMPSYN_S3_REGION_NAME: us-east-1 
        COMPSYN_S3_BUCKET: comp-syn-pytest 
        COMPSYN_BROWSER: Firefox
      run: |
        container=$(docker run -d ialcloud/comp-syn-base:1.0.0 sleep 60) && docker cp ${container}:/home/admin/jzazbz_array.npy . && poetry run pytest --cov=compsyn -s
