name: Test (on PR)
on:
  pull_request: 

jobs:
  test:
    environment: ci
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/docker-compose.yml
      COMPSYN_S3_ACCESS_KEY_ID: ${{ secrets.COMPSYN_S3_ACCESS_KEY_ID }}
      COMPSYN_S3_SECRET_ACCESS_KEY: ${{ secrets.COMPSYN_S3_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: docker-compose build

    - name: Run non-credentialed pytest coverage 
      run: |
        docker-compose --env-file ./.ci/.env.pytest run comp-syn python3.8 -m pytest -m "unit or integration or online" -s
